## Why Remove dupes
- maintain accurate, consistent datasets
- avoid producing misleading statistics

In [ ]:
import numpy as np, pandas as pd
from pandas import Series, DataFrame

## REmoving duplicates breva

In [2]:
df = DataFrame({'column 1': [1, 1, 2, 2, 3, 3, 3],
'column 2':['a', 'a', 'b', 'b', 'c', 'c', 'c'],
'column 3':['A', 'A', 'B', 'B', 'C', 'C', 'C']})
df

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        C
6         3        c        C

In [3]:
# use duplicate method which shows us the duplicates
df.duplicated()

0    False
1     True
2    False
3     True
4    False
5     True
6     True
dtype: bool

In [5]:
# drop duplicates in the df
df.drop_duplicates()

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C

In [6]:
df = DataFrame({'column 1': [1, 1, 2, 2, 3, 3, 3],
'column 2':['a', 'a', 'b', 'b', 'c', 'c', 'c'],
'column 3':['A', 'A', 'B', 'B', 'C', 'C', 'D']})
df

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        C
6         3        c        D

In [7]:
# drop based on column values, using axis = 1
df.drop_duplicates('column 3')

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C
6         3        c        D